### PR TITLE
"finishAll" functionality

### PR DESCRIPTION
**Pull request by phopkins**
Adds an option to finish all animations on an element's queue, not
just the currently-running one.

### CODE REVIEW

**Comment by ydaniv** [comment]
Why so many changes in the jQuery shim part?

**Comment by phopkins** [comment]
I think the original had inconsistent line endings.

**Comment by ydaniv** [comment]
@julianshapiro perhaps you're to blame in all this line endings fiesco? :stuck_out_tongue:

**Comment by Rycochet** [comment]
There's a git option to ignore line endings, technically it would be everyone pushing without that option set that's at fault ;-)

**Comment by ydaniv** [comment]
:+1:

**Pull request merged**
