### PR TITLE
Select correct ticker function during initialization, not only when document visibility changes

### LINKED ISSUE #611: Internal reference to requestAnimationFrame is not being replaced with wrapped setTimeout during execution time
Little over a year ago a problem with native implementation of  `requestAnimationFrame` was reported. Any repainting (actually execution of passed functions) queued while page is resting on the background are being delayed and executed only when tab becomes visible (#176 - requestAnimationFrame background handling). 

It was fixed later in 5508fea, however fix wasn't quite perfect. For some reason check if page is hidden or not only being made when this state changes, implying it's always visible during loading and execution time, which is false. So if page happened to be on the background when Velocity's  code was executed - every animation still will be delayed and played only when tab will become visible.

Unless there was a reason for this (I don't see any), I think [event subscription](//github.com/julianshapiro/velocity/blob/f28c610da721048abee0be4f88a5d32d71ae8ea4/velocity.js#L3336..L3351) code should be changed to something like

``` javascript
if (!Velocity.State.isMobile && document.hidden !== undefined) {
    function spoofTicker() {
        /* Reassign the rAF function (which the global tick() function uses) based on the tab's focus state. */
        if (document.hidden) {
            ticker = function(callback) {
                /* The tick function needs a truthy first argument in order to pass its internal timestamp check. */
                return setTimeout(function() { callback(true) }, 16);
            };

            /* The rAF loop has been paused by the browser, so we manually restart the tick. */
            tick();
        } else {
            ticker = window.requestAnimationFrame || rAFShim;
        }
    }

    document.addEventListener("visibilitychange", spoofTicker);
    spoofTicker();
}
```

but with a better name for the function than the one I came up with. 

That's probably unnecessary, but here's a [very basic fiddle](http://fiddle.jshell.net/3d3bhsdh/show/) you can observe problem at. (Just click the link with Mouse3 button or Ctrl+Mouse1 to open it in a new tab without switching to it). After page is loaded wait for more than 2 seconds (that's the duration of initialized animation) and switch to it - you will see animation playing.

### PR DESCRIPTION
**Pull request by Iwasawafag**
Fixes #611

### CODE REVIEW

**Comment by Iwasawafag** [comment]
ugh, it didn't work. I'm pretty sure it did when I tested it year ago

**Comment by Rycochet** [comment]
Was finishing up getting the pause in and eyeing this up next, any idea why it doesn't fix it?

**Comment by Iwasawafag** [comment]
I'm not sure yet. Animation starts playing in the background as it supposed to, but instead of stopping at the end it plays it backwards to initial state with the same speed, then forward again and so on. I was thinking it might be because of `tick()` call which is unnecessary upon initialization, but that's not it.

I'll take another look this evening (in like 6 hours)

**Comment by Rycochet** [comment]
I run a D&D game on Thursday evenings, so won't be able to look till tomorrow anyway - and trying to update QUnit to v2 to improve the testing right now ;-)

**Comment by Iwasawafag** [comment]
Hi. Diidn't had time to take a look into this yesterday, so I'm just getting started. Something has changed indeed. I tried to roll back to ce90611 (year ago), apply the patch and it did the thing. Also works with 1.3.1, but breaks on 1.3.2 release.

I also noticed another new behavior with 1.3.2, which is not mentioned in release notes: **all running animations are getting fast-forwarded to the end with the next tick after tab is moved to background**. 

Here's JSFiddle: [1.3.1](http://fiddle.jshell.net/Iwasawafag/kpbeg8y6/1/) and [1.3.2](http://fiddle.jshell.net/Iwasawafag/kpbeg8y6/2/). I don't know if it's intended or not. I can definitely see how this could be a desired behavior, but personally I would consider this a breaking change.

Thought, I would let you know asap. Will keep you updated.

**Comment by Iwasawafag** [comment]
Caused by 130d2e6.

**Comment by Iwasawafag** [comment]
So, to summ this up, what should be done is:

- 130d2e6 should probably be rolled back and fixed
- Rewrite function we're assigning to `ticker` when page goes to background ~~so it would resemble implementation from `rAFShim` more and would pass correct time since last call in first argument rather than `true`. I think it's also safe to lower framerate twice there, even though browsers slow down setTimeouts themselves.....~~ Actually, since browsers do delay setTimeouts for background tabs we could rely on this behavior and just use setTimeout-based implementation from `rAFShim` - just need to make it visible to other parts of Velocity code. And there also will be less dupplicated code. At which point `timestamp` option will not be needed?

Expect another pull request landing in few minutes. I'm too lazy to create an issue for this bug though, so if you use them for tracking various problems - you might want to create one yourself.

**Comment by Rycochet** [comment]
Not going to roll that back - but definitely needs fixing - if it's in the background then it should use the "normal" time, and not the high resolution time.

**Comment by Rycochet** [comment]
Hopefully this fixes it - can't have a "perfect" timer as the start time isn't known, but looks to be within a couple of ms of the expected time to me - which should hopefully let this PR work properly again :-)

**Comment by Iwasawafag** [comment]
> Hopefully this fixes it - can't have a "perfect" timer as the start time isn't known

Here was [my take on this](https://github.com/Iwasawafag/velocity/commit/910c6ba226d4eb094596da416ad914c3f1a801fb). Instead of creating local polifyll for `performance.now()` I updated `rAFShim`. It uses `performance.now()` when present, so we can safely interchange it with native implementation of `requestAnimationFrame` and timestamp returned to callback will be on the same scale.

When `performance.now()` is not available - native version of requestAnimationFrame probably isn't present as well, so we shouldn't care, but `timeCurrent` is measured from the moment code definyning polifill was executed. 

With this 

```js
var timeCurrent = Velocity.timestamp && timestamp !== true ? timestamp : performance.now();
```

could be simplified to 

```js
var timeCurrent = timestamp;
```

....

Now thinking of what I did with timestamps when performance API is not available, that might lead to problems in environments where `window.requestAnimationFrame` was monkey patched. Because verison from another polifyll will probably use just `new Date().getTime()` returned to the callback.

With all this in mind, I think you should update that line to simply

```js
var timeCurrent = performance.now();
```

Only this way we know for sure returned values will be count from the same origin in every situation.

**Comment by Iwasawafag** [comment]
> which should hopefully let this PR work properly again :-)

Can confirm - it works properly as is with current master. It's up to you now

**Comment by Rycochet** [comment]
Checking on MDN, `performance.now()` is available somewhat later than `requestAnimationFrame` (but both quite a few years ago) - so either way works.

If you look at #684 (specifically the graphs in it) you can see that `performance.now()` is definitely not good enough for normal use (it's barely better than `Date.now()`) - so it does need to use the rAF timestamp when available. The possibility of a "broken" `performance.now()` polyfill is there - but as Velocity is planning on dropping the legacy browsers that don't support it at some point I think it's ok to use.

Saying that, it might be worth improving the new polyfill code to try and detect broken API access - maybe check for decimal places, and if none then assume broken?

Not quite sure how we can make this part of the test suite either...

**Pull request merged**
