### PR TITLE
Remove jQuery dependency from package.json

### PR DESCRIPTION
**Pull request by freeqaz**
https://github.com/julianshapiro/velocity/issues/497

### CODE REVIEW

**Comment by freeqaz** [comment]
bumpin'

**Comment by michealparks** [comment]
Second bump, would love to have npm not pull jquery with this repo

**Comment by gonsfx** [comment]
Bump!

**Comment by Rycochet** [comment]
Going to leave this in place till v2 simply so nothing changes for v1

**Comment by rileybracken** [comment]
@Rycochet I would love to use VelocityJS the only thing that is preventing me from using it is the jQuery dependency.

Is there certain issues we can help with to move v2 to a alpha build?

**Comment by Rycochet** [comment]
Somehow this made it in, and I never even noticed :-)

**Pull request closed without merging**
