### PR TITLE
Allow infinite loop on counterclockwise rotateZ

### PR DESCRIPTION
**Pull request by allofthesepeople**
In the same way a value of 360 reset to 0 rather than step backwards, so should a value of -360; allowing for counterclockwise infinite rotate.

### CODE REVIEW

**Comment by ydaniv** [comment]
:+1:

**Comment by r4j4h** [comment]
+1

**Comment by Rycochet** [comment]
Just as a pair of minor comments - regex is relatively expensive in terms of cycles - so having the check once and wrapping the value checks is slightly nicer. Secondly it might be better to parse the float, and then add (or remove) 360 degrees, so if it doesn't have nice easy numbers it can still go right around ;-)

**Comment by allofthesepeople** [comment]
@Rycochet agreed, I was wanting to just keep things as readable as possible & copying the previous block was the easiest way to do that. The following 3 lines may be better than the 6 in the request.

```javascript
if (/^rotate/.test(propertyName) && Math.abs(tweenContainer.endValue) === 360) {
  tweenContainer.startValue = tweenContainer.endValue;
  tweenContainer.endValue = 0;
}
```

**Comment by Rycochet** [comment]
Nice :-) My final comment is - how are we sure that it's 0->360, and not say 180->360? Swap the values properly, or check that it's startValue is 0?

**Comment by allofthesepeople** [comment]
Ah, my understanding was the previous worked (checking for +360 only) & went from there.

**Comment by Rycochet** [comment]
It did - but as you're in there and fixing code anyway... :-P

**Comment by allofthesepeople** [comment]
It would, obviously, be possible to check for any difference between start & end equal to 360 & then apply the above, but that would be a little bigger change than just 0 -> ±360 and might break some people’s current usage. Might want an opinion from @julianshapiro before making that change but something like this should work for that:

```javascript
if (/^rotate/.test(propertyName) && ((tweenContainer.startValue - tweenContainer.endValue)%360 === 0)) {
  var start = tweenContainer.startValue;
  tweenContainer.startValue = tweenContainer.endValue;
  tweenContainer.endValue = start;
}
```

**Comment by Rycochet** [comment]
That final bit of code is pretty much perfect, just got to cross fingers and hope @julianshapiro likes it (it doesn't break anything, and would fix the bug where a non-360 degree loop gets looped wrongly) :+1: :-)

**Comment by allofthesepeople** [comment]
related to: #453

**Comment by ydaniv** [comment]
A more correct approach is here #551

**Comment by Rycochet** [comment]
Manually merged

**Pull request closed without merging**
