### PR TITLE
Minimal fix for #885: Animations don't work in IE11

### PR DESCRIPTION
**Pull request by wagich**
#### Checklist

* Have you linked to relevant open issues?:
https://github.com/julianshapiro/velocity/issues/885
* I agree for this to be covered by the Velocity [license](https://github.com/julianshapiro/velocity/blob/master/LICENSE.md)?:
Yes, I agree

#### Please describe this Pull Request in as much detail as possible:
As stated in #885, there is a problem running animations in IE11. I traced it to the utility function `getValue`, which tries to iterate `arguments`. This works in browsers with proper iterator support, but falls apart otherwise. The problem lies in `arguments` being of type `object` and not `array` so we can't really polyfill it (see https://github.com/babel/babel/issues/1181).

With this PR, the `args` variable is iterated instead, since it is a proper array and can be polyfilled. The `args`-array is created and filled anyway https://github.com/julianshapiro/velocity/blob/e238e873b5d22bf41f5f1823e9bb43022f3eb08e/velocity.es5.js#L150-L152 so this should be of minimal impact.

#### People who contributed to this change:
Michael Wagner

### CODE REVIEW

**Comment by wagich** [comment]
To add: you still need to polyfill everything that IE11 doesn't support natively – it's just that it is now possible to run using the appropriate polyfills instead of not at all.

**Comment by Rycochet** [comment]
I can't say when I'll have time to do this, but this is a good start for the problem - will see if I can get an automatic legacy build in for the polyfills at the same time...

**Comment by vojty** [comment]
spent few ours debugging before I found this :/ could you please release new version @Rycochet ?

**Comment by Rycochet** [comment]
@vojty I want to - but after merging this I started to update to the latest Typescript, and found quite a few potential bugs on the way - then ran out of time with it again - will try to finish the update and get things out this weekend!

**Comment by Rycochet** [comment]
@vojty Pushed a new version today, planning to do some work on it over the weekend, so hopefully the other issues get fixed too!

**Pull request merged**
